name: tdd-practice
version: 0.1.0.0
homepage:            https://github.com/tooppoo/tdd-practice
license:             MIT
license-file:        LICENSE
author:              philomagi
maintainer:          philomagi<tooppoo56@gmail.com>
copyright:           2021 philomagi
build-type:          Simple
extra-source-files:  README.md

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5

tests:
  tdd-practice-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tdd-practice
    - hspec
    - hspec-discover
    - QuickCheck
